/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import controller.ControllerFormaPagamento;
import java.util.ArrayList;
import model.ModelFormaPagamento;
import util.BLMascaras;

/**
 *
 * @author Mr-Robot
 */
public class ViewPagamentoPDV extends javax.swing.JDialog {
    //INSTANCIAS
    ControllerFormaPagamento controllerFormaPagamento = new ControllerFormaPagamento();
    ArrayList<ModelFormaPagamento> listaModelFormaPagamentos = new ArrayList<>();
    ModelFormaPagamento modelFormaPagamento = new ModelFormaPagamento();
    
    BLMascaras blm = new BLMascaras();
    
    //VARIAVEIS GLOBAIS
    private float valorTotal;
    private float desconto;
    private float valorRecebido;
    private float troco;
    private String formaPagamento;
    private boolean pagou;
    
    
    /** Creates new form ViewPagamentoPDV */
    public ViewPagamentoPDV(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.listaFormaPagamento();
        this.pagou = false;
        this.calcularPagamento();
        this.limparCampos();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrincipal = new javax.swing.JPanel();
        jPanelCalculo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jFTF_SubTotal = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jFTF_Desconto = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jFTF_ValorRecebido = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jCBox_Pagamento = new javax.swing.JComboBox<>();
        jPanelValorTotalPagar = new javax.swing.JPanel();
        jL_ValorTotal = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jB_Ok = new javax.swing.JButton();
        jFTF_Troco = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Forma de Pagamento");

        jPanelCalculo.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("SubTotal:");

        jFTF_SubTotal.setEditable(false);
        jFTF_SubTotal.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Desconto:");

        jFTF_Desconto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFTF_DescontoFocusLost(evt);
            }
        });
        jFTF_Desconto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFTF_DescontoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Valor Recebido:");

        jFTF_ValorRecebido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFTF_ValorRecebidoFocusLost(evt);
            }
        });
        jFTF_ValorRecebido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFTF_ValorRecebidoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Pagamento:");

        jCBox_Pagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCBox_Pagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBox_PagamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCalculoLayout = new javax.swing.GroupLayout(jPanelCalculo);
        jPanelCalculo.setLayout(jPanelCalculoLayout);
        jPanelCalculoLayout.setHorizontalGroup(
            jPanelCalculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCalculoLayout.createSequentialGroup()
                .addGroup(jPanelCalculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCalculoLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanelCalculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelCalculoLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel2)))
                        .addGap(30, 30, 30)
                        .addGroup(jPanelCalculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFTF_SubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCBox_Pagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFTF_Desconto, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFTF_ValorRecebido, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelCalculoLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel1))
                    .addGroup(jPanelCalculoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanelCalculoLayout.setVerticalGroup(
            jPanelCalculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCalculoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanelCalculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jFTF_SubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCalculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCBox_Pagamento, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCalculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFTF_Desconto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanelCalculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jFTF_ValorRecebido, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanelValorTotalPagar.setBackground(new java.awt.Color(153, 204, 255));
        jPanelValorTotalPagar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Valor Total a Pagar", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 18))); // NOI18N

        jL_ValorTotal.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jL_ValorTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_ValorTotal.setText("0");

        javax.swing.GroupLayout jPanelValorTotalPagarLayout = new javax.swing.GroupLayout(jPanelValorTotalPagar);
        jPanelValorTotalPagar.setLayout(jPanelValorTotalPagarLayout);
        jPanelValorTotalPagarLayout.setHorizontalGroup(
            jPanelValorTotalPagarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jL_ValorTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelValorTotalPagarLayout.setVerticalGroup(
            jPanelValorTotalPagarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelValorTotalPagarLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jL_ValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel5.setText("Troco:");

        jB_Ok.setText("Ok");
        jB_Ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_OkActionPerformed(evt);
            }
        });

        jFTF_Troco.setEditable(false);
        jFTF_Troco.setEnabled(false);
        jFTF_Troco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFTF_TrocoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPrincipalLayout = new javax.swing.GroupLayout(jPanelPrincipal);
        jPanelPrincipal.setLayout(jPanelPrincipalLayout);
        jPanelPrincipalLayout.setHorizontalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                        .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                                .addComponent(jPanelCalculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jPanelValorTotalPagar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFTF_Troco, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jB_Ok)
                        .addGap(26, 26, 26))))
        );
        jPanelPrincipalLayout.setVerticalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCalculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelValorTotalPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jB_Ok))
                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jFTF_Troco)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB_OkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_OkActionPerformed
        
    }//GEN-LAST:event_jB_OkActionPerformed

    private void jFTF_DescontoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFTF_DescontoFocusLost
        jFTF_Desconto.setText(blm.converterVirgulaParaPonto(jFTF_Desconto.getText()));
        calcularPagamento();
    }//GEN-LAST:event_jFTF_DescontoFocusLost

    private void jFTF_ValorRecebidoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFTF_ValorRecebidoFocusLost
        jFTF_ValorRecebido.setText(blm.converterVirgulaParaPonto(jFTF_ValorRecebido.getText()));
        calcularPagamento();
    }//GEN-LAST:event_jFTF_ValorRecebidoFocusLost

    private void jFTF_TrocoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFTF_TrocoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFTF_TrocoActionPerformed

    private void jFTF_DescontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFTF_DescontoActionPerformed
        jFTF_ValorRecebido.requestFocus();
    }//GEN-LAST:event_jFTF_DescontoActionPerformed

    private void jFTF_ValorRecebidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFTF_ValorRecebidoActionPerformed
        //Finalizar o pagamento
        //AÇÃO DO ENTER
        this.formaPagamento = jCBox_Pagamento.getSelectedItem().toString();
        this.desconto = Float.parseFloat(this.jFTF_Desconto.getText());
        this.valorRecebido = Float.parseFloat(this.jFTF_ValorRecebido.getText());
        this.valorTotal = Float.parseFloat(this.jL_ValorTotal.getText());
        this.troco = Float.parseFloat(this.jFTF_Troco.getText());
        this.pagou = true;
        dispose();
    }//GEN-LAST:event_jFTF_ValorRecebidoActionPerformed

    private void jCBox_PagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBox_PagamentoActionPerformed
        jFTF_Desconto.requestFocus();
    }//GEN-LAST:event_jCBox_PagamentoActionPerformed
    
    private void limparCampos(){
        jFTF_Desconto.setText("0");
        jFTF_ValorRecebido.setText("0");
    }
    
    /**
     * Calcular o valor total a pagar e troco
     */
    private void calcularPagamento(){
        //Variaveis
        float subTotal, desconto, recebido, pagar, troco;
        
        //Tratamento de Excep com try
        try {
            subTotal = Float.parseFloat(jFTF_SubTotal.getText());
        } catch (Exception e) {
            subTotal = 0;
        }
        try {
            desconto = Float.parseFloat(jFTF_Desconto.getText());
        } catch (Exception e) {
            desconto = 0;
            jFTF_Desconto.setText("0");
        }
        try {
            recebido = Float.parseFloat(jFTF_ValorRecebido.getText());
        } catch (Exception e) {
            recebido = 0;
            jFTF_ValorRecebido.setText("0");
        }
//        //tratando Excep com if obs: Não indicado
//        //VERIFICAÇÃO SER O VALOR É NULA("")
//        if (!jFTF_Desconto.getText().equals("")) {
//            desconto = Float.parseFloat(jFTF_Desconto.getText());
//        } else {
//            desconto = 0;
//        }//final de DESCONTO
//        
//        //VERIFICAÇÃO SER O VALOR É NULA("")
//        if (!jFTF_ValorRecebido.getText().equals("")) {
//            recebido = Float.parseFloat(jFTF_ValorRecebido.getText());
//        } else {
//            recebido = 0;
//        }//final de VALOR RECEBIDO
        
        //CALCULAR VALOR A PAGAR
        pagar = subTotal - desconto;
        jL_ValorTotal.setText(blm.arredondamentoComPontoDuasCasasString(pagar));
        //CALCULAR VALOR A PAGAR
        troco = recebido - pagar;
        //pegando o valor obs: tratar excep com (+ "")concartenação
        jFTF_Troco.setText(blm.arredondamentoComPontoDuasCasasString(troco));
                
    }
    
    /**
     * Preenche o comboBox com todas formas de pagamentos
     */
    private void listaFormaPagamento(){
        listaModelFormaPagamentos = controllerFormaPagamento.getListaFormaPagamentoController();
        jCBox_Pagamento.removeAllItems();
        for (int i = 0; i < listaModelFormaPagamentos.size(); i++) {
            jCBox_Pagamento.addItem(listaModelFormaPagamentos.get(i).getDescricaoForPag());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPagamentoPDV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPagamentoPDV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPagamentoPDV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPagamentoPDV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ViewPagamentoPDV dialog = new ViewPagamentoPDV(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_Ok;
    private javax.swing.JComboBox<String> jCBox_Pagamento;
    private javax.swing.JFormattedTextField jFTF_Desconto;
    private javax.swing.JFormattedTextField jFTF_SubTotal;
    private javax.swing.JFormattedTextField jFTF_Troco;
    private javax.swing.JFormattedTextField jFTF_ValorRecebido;
    private javax.swing.JLabel jL_ValorTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanelCalculo;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JPanel jPanelValorTotalPagar;
    // End of variables declaration//GEN-END:variables

    
    public void setFormatedTextFielValorTotal(){
        this.jFTF_SubTotal.setText(this.valorTotal + "");
    }
    
    /**
     * @return the valorTotal
     */
    public float getValorTotal() {
        return valorTotal;
    }

    /**
     * @param valorTotal the valorTotal to set
     */
    public void setValorTotal(float valorTotal) {
        this.valorTotal = valorTotal;
    }

    /**
     * @return the desconto
     */
    public float getDesconto() {
        return desconto;
    }

    /**
     * @param desconto the desconto to set
     */
    public void setDesconto(float desconto) {
        this.desconto = desconto;
    }

    /**
     * @return the valorRecebido
     */
    public float getValorRecebido() {
        return valorRecebido;
    }

    /**
     * @param valorRecebido the valorRecebido to set
     */
    public void setValorRecebido(float valorRecebido) {
        this.valorRecebido = valorRecebido;
    }

    /**
     * @return the troco
     */
    public float getTroco() {
        return troco;
    }

    /**
     * @param troco the troco to set
     */
    public void setTroco(float troco) {
        this.troco = troco;
    }

    /**
     * @return the formaPagamento
     */
    public String getFormaPagamento() {
        return formaPagamento;
    }

    /**
     * @param formaPagamento the formaPagamento to set
     */
    public void setFormaPagamento(String formaPagamento) {
        this.formaPagamento = formaPagamento;
    }

    /**
     * @return the pagou
     */
    public boolean isPagou() {
        return pagou;
    }

    /**
     * @param pagou the pagou to set
     */
    public void setPagou(boolean pagou) {
        this.pagou = pagou;
    }

}
