/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControllerProdutos;
import controller.ControllerVendas;
import controller.ControllerVendasProdutos;
import java.util.ArrayList;
import model.ModelProdutos;
import model.ModelSessaoUsuario;
import model.ModelVendas;
import model.ModelVendasProdutos;
import util.BLDatas;
import util.BLMascaras;

/**
 *
 * @author Mr-Robot
 */
public class ViewTestePDV extends javax.swing.JFrame {

    //Instanciando o Conversor de datas
    BLDatas bLDatas = new BLDatas();
    
    ControllerProdutos controllerProdutos = new ControllerProdutos();
    ModelProdutos modelProdutos = new ModelProdutos();
    ModelVendas modelVendas = new ModelVendas();
    ModelVendasProdutos modelVendasProdutos = new ModelVendasProdutos();
    ArrayList<ModelVendasProdutos> listaModelVendasProdutos = new ArrayList<>();
    ArrayList<ModelProdutos> listaModelProdutos = new ArrayList<>();
    ControllerVendas controllerVendas = new ControllerVendas();
    ControllerVendasProdutos controllerVendasProdutos = new ControllerVendasProdutos();
    ModelSessaoUsuario modelSessaoUsuario = new ModelSessaoUsuario();
    
    BLMascaras blMascara = new BLMascaras();
    
    //Instanciando Tela de pagamento PDV
    private ViewPagamentoPDV viewPagamentoPDV;
    
    int QUANTIDADE;
    
    /**
     * Creates new form ViewTestePDV
     */
    public ViewTestePDV() {
        initComponents();
        
        //Chamando metodos globais
        setLocationRelativeTo(null);
        //Maximinizando Tela PDV
        //setExtendedState(JFrame.MAXIMIZED_BOTH);
        //padrão a quantidade
        QUANTIDADE = 1;
        //setarOperador();
        
        //Chamando  a TELA PAGAMENTO
        //this.viewPagamentoPDV = new ViewPagamentoPDV(this, true);
        //this.limparTela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTeste = new javax.swing.JPanel();
        jPanelTENS_ADD = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTB_ITENS = new javax.swing.JTable();
        jBExcluir = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();
        jFormattedTextField9 = new javax.swing.JFormattedTextField();
        jPanelCOD_BARRAS = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jFTFCodBarras = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanelCaixa = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLb_Caixa = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLb_Operador = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLb_Status = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanelCALCULO = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jFormattedTextField3 = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        jFormattedTextField4 = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        jFormattedTextField5 = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        jFormattedTextField6 = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        jFormattedTextField7 = new javax.swing.JFormattedTextField();
        jLabel15 = new javax.swing.JLabel();
        jFormattedTextField8 = new javax.swing.JFormattedTextField();
        jLabel19 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMI_Sair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMI_ExcluirProduto = new javax.swing.JMenuItem();
        jMI_ComAlteraQtdProd = new javax.swing.JMenuItem();
        jMt_ComFinalizarVenda = new javax.swing.JMenuItem();
        jMI_ComPesqProd = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelTeste.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanelTENS_ADD.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 0));
        jLabel1.setText("ITENS ADICIONADOS");

        jTB_ITENS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Núm. Venda", "Produto", "Quantidade", "Valor Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTB_ITENS);
        if (jTB_ITENS.getColumnModel().getColumnCount() > 0) {
            jTB_ITENS.getColumnModel().getColumn(0).setMinWidth(80);
            jTB_ITENS.getColumnModel().getColumn(0).setPreferredWidth(80);
            jTB_ITENS.getColumnModel().getColumn(0).setMaxWidth(80);
            jTB_ITENS.getColumnModel().getColumn(2).setMinWidth(90);
            jTB_ITENS.getColumnModel().getColumn(2).setPreferredWidth(90);
            jTB_ITENS.getColumnModel().getColumn(2).setMaxWidth(90);
            jTB_ITENS.getColumnModel().getColumn(3).setMinWidth(130);
            jTB_ITENS.getColumnModel().getColumn(3).setPreferredWidth(130);
            jTB_ITENS.getColumnModel().getColumn(3).setMaxWidth(130);
        }

        jBExcluir.setText("Excluir");
        jBExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExcluirActionPerformed(evt);
            }
        });

        jBCancelar.setText("Cancelar");

        jFormattedTextField9.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jFormattedTextField9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanelTENS_ADDLayout = new javax.swing.GroupLayout(jPanelTENS_ADD);
        jPanelTENS_ADD.setLayout(jPanelTENS_ADDLayout);
        jPanelTENS_ADDLayout.setHorizontalGroup(
            jPanelTENS_ADDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTENS_ADDLayout.createSequentialGroup()
                .addGroup(jPanelTENS_ADDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTENS_ADDLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jBExcluir)
                        .addGap(50, 50, 50)
                        .addComponent(jBCancelar))
                    .addGroup(jPanelTENS_ADDLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelTENS_ADDLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jFormattedTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        jPanelTENS_ADDLayout.setVerticalGroup(
            jPanelTENS_ADDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTENS_ADDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jFormattedTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelTENS_ADDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBExcluir)
                    .addComponent(jBCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelCOD_BARRAS.setBackground(new java.awt.Color(204, 204, 255));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("CÓDIGO DE BARRAS");

        jFTFCodBarras.setEditable(false);

        jLabel3.setText("Descrição/Produto");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Cliente");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Quantidade");

        jFormattedTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Preço Unitário");

        jFormattedTextField2.setEditable(false);
        jFormattedTextField2.setEnabled(false);
        jFormattedTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField2ActionPerformed(evt);
            }
        });

        jLabel7.setText("Estoque");

        jTextField1.setEditable(false);
        jTextField1.setEnabled(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("COMANDOS DE ATALHOS");

        jPanelCaixa.setBackground(new java.awt.Color(255, 255, 255));

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel16.setText("Caixa:");

        jLb_Caixa.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLb_Caixa.setText("Caixa");

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel17.setText("Operador:");

        jLb_Operador.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLb_Operador.setText("Operador");

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel18.setText("Status:");

        jLb_Status.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLb_Status.setText("Status");

        javax.swing.GroupLayout jPanelCaixaLayout = new javax.swing.GroupLayout(jPanelCaixa);
        jPanelCaixa.setLayout(jPanelCaixaLayout);
        jPanelCaixaLayout.setHorizontalGroup(
            jPanelCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCaixaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLb_Caixa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLb_Operador, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                    .addComponent(jLb_Status, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanelCaixaLayout.setVerticalGroup(
            jPanelCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCaixaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLb_Caixa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLb_Operador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLb_Status))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel20.setText("F2 - Excluir");

        jLabel21.setText("F3 - Quantidade");

        jLabel22.setText("F4 - Finalizar Venda");

        jLabel23.setText("F5 - Pesquisar Produto");

        jLabel24.setText("F6 - Sair do PDV");

        jLabel25.setText("Ctrl + Alt + E - Fechar todo o Sistema");

        javax.swing.GroupLayout jPanelCOD_BARRASLayout = new javax.swing.GroupLayout(jPanelCOD_BARRAS);
        jPanelCOD_BARRAS.setLayout(jPanelCOD_BARRASLayout);
        jPanelCOD_BARRASLayout.setHorizontalGroup(
            jPanelCOD_BARRASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCOD_BARRASLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCOD_BARRASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCOD_BARRASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanelCOD_BARRASLayout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel7))
                        .addComponent(jFTFCodBarras)
                        .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCOD_BARRASLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel8))
                    .addComponent(jPanelCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelCOD_BARRASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanelCOD_BARRASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24)
                            .addComponent(jLabel20))
                        .addGroup(jPanelCOD_BARRASLayout.createSequentialGroup()
                            .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(29, 29, 29)
                            .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanelCOD_BARRASLayout.setVerticalGroup(
            jPanelCOD_BARRASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCOD_BARRASLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFTFCodBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCOD_BARRASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCOD_BARRASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelCALCULO.setBackground(new java.awt.Color(255, 204, 204));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setText("TOTAL");

        jFormattedTextField3.setEditable(false);
        jFormattedTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField3.setText("-");
        jFormattedTextField3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jFormattedTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField3ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setText("SUB TOTAL");

        jFormattedTextField4.setEditable(false);
        jFormattedTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField4.setText("0");
        jFormattedTextField4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jFormattedTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField4ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel12.setText("DESCONTO");

        jFormattedTextField5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jFormattedTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField5ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel13.setText("TOTAL DA COMPRA");

        jFormattedTextField6.setEditable(false);
        jFormattedTextField6.setForeground(new java.awt.Color(0, 102, 102));
        jFormattedTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField6.setText("-");
        jFormattedTextField6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jFormattedTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField6ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel14.setText("VALOR RECEBIDO");

        jFormattedTextField7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jFormattedTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField7ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel15.setText("TROCO");

        jFormattedTextField8.setEditable(false);
        jFormattedTextField8.setForeground(new java.awt.Color(255, 51, 51));
        jFormattedTextField8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField8.setText("-");
        jFormattedTextField8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jFormattedTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField8ActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel19.setText("PAGAMENTO");

        jComboBox3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleciona Forma Pagamento", "Pagamento a Vista", "Pagamento no Cartão" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCALCULOLayout = new javax.swing.GroupLayout(jPanelCALCULO);
        jPanelCALCULO.setLayout(jPanelCALCULOLayout);
        jPanelCALCULOLayout.setHorizontalGroup(
            jPanelCALCULOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCALCULOLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCALCULOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jFormattedTextField3)
                    .addComponent(jFormattedTextField4)
                    .addComponent(jFormattedTextField5)
                    .addComponent(jFormattedTextField6)
                    .addComponent(jFormattedTextField7)
                    .addComponent(jFormattedTextField8)
                    .addComponent(jLabel19)
                    .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelCALCULOLayout.setVerticalGroup(
            jPanelCALCULOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCALCULOLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelTesteLayout = new javax.swing.GroupLayout(jPanelTeste);
        jPanelTeste.setLayout(jPanelTesteLayout);
        jPanelTesteLayout.setHorizontalGroup(
            jPanelTesteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTesteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelTENS_ADD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelCOD_BARRAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelCALCULO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelTesteLayout.setVerticalGroup(
            jPanelTesteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTesteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTesteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanelCOD_BARRAS, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelTENS_ADD, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelCALCULO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 51, 0));
        jLabel9.setText("PDV DE VENDAS");

        jMenu1.setText("Arquivos");

        jMI_Sair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        jMI_Sair.setText("Sair");
        jMI_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMI_SairActionPerformed(evt);
            }
        });
        jMenu1.add(jMI_Sair);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Comandos");

        jMI_ExcluirProduto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        jMI_ExcluirProduto.setText("Excluir Produtos");
        jMI_ExcluirProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMI_ExcluirProdutoActionPerformed(evt);
            }
        });
        jMenu2.add(jMI_ExcluirProduto);

        jMI_ComAlteraQtdProd.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        jMI_ComAlteraQtdProd.setText("Alterar quantidade");
        jMI_ComAlteraQtdProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMI_ComAlteraQtdProdActionPerformed(evt);
            }
        });
        jMenu2.add(jMI_ComAlteraQtdProd);

        jMt_ComFinalizarVenda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        jMt_ComFinalizarVenda.setText("Finalizar Venda");
        jMt_ComFinalizarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMt_ComFinalizarVendaActionPerformed(evt);
            }
        });
        jMenu2.add(jMt_ComFinalizarVenda);

        jMI_ComPesqProd.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        jMI_ComPesqProd.setText("Pesquisar Produtos");
        jMenu2.add(jMI_ComPesqProd);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelTeste, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(429, 429, 429)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelTeste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBExcluirActionPerformed

    private void jFormattedTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField1ActionPerformed

    private void jFormattedTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField2ActionPerformed

    private void jFormattedTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField4ActionPerformed

    private void jFormattedTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField6ActionPerformed

    private void jFormattedTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField7ActionPerformed

    private void jFormattedTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField8ActionPerformed

    private void jFormattedTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField3ActionPerformed

    private void jFormattedTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField5ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jMI_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMI_SairActionPerformed
        dispose();
    }//GEN-LAST:event_jMI_SairActionPerformed

    private void jMI_ExcluirProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMI_ExcluirProdutoActionPerformed
//        //ordenando linha depois das exclusões
//        int quantLinha = jTbPDV.getRowCount();
//        //comparação ser tem itens na lista
//        if (quantLinha < 1) {
//            JOptionPane.showMessageDialog(rootPane, "Não existe itens para excluir!", "ATENÇÃO!", JOptionPane.WARNING_MESSAGE);
//        } else { // Caso tenha excluar
//            DefaultTableModel modelo = (DefaultTableModel)jTbPDV.getModel();
//            //Pegando a linha para excluir
//            int linha = Integer.parseInt(JOptionPane.showInputDialog("Informe o item que deseja excluir! "));
//            // removendo uma linha
//            modelo.removeRow(linha-1);
//            //somando item restantes
//            jFTF_ValorBruto.setText(String.valueOf(somaValorTotal()));
//
//            for (int i = 0; i < quantLinha; i++) {
//                modelo.setValueAt(i + 1, i, 0);
//            }
//        }
    }//GEN-LAST:event_jMI_ExcluirProdutoActionPerformed

    private void jMI_ComAlteraQtdProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMI_ComAlteraQtdProdActionPerformed
//        // TODO add your handling code here:
//        //setando a quantidade para somatório
//        QUANTIDADE = Integer.parseInt(JOptionPane.showInputDialog("Informe a quantidade!"));
    }//GEN-LAST:event_jMI_ComAlteraQtdProdActionPerformed

    private void jMt_ComFinalizarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMt_ComFinalizarVendaActionPerformed
//        try {
//            this.viewPagamentoPDV = new ViewPagamentoPDV(this, true);
//            //Pegando o valor Total
//            viewPagamentoPDV.setValorTotal(Float.parseFloat(jFTF_ValorBruto.getText()));
//            //Setando no metodos da viewPagamentoPDV e jogando o valor na view
//            viewPagamentoPDV.setFormatedTextFielValorTotal();
//            //Mostrando Tela PagamentoPDV
//            viewPagamentoPDV.setVisible(true);
//
//            System.out.println(viewPagamentoPDV.getFormaPagamento());
//
//            if (viewPagamentoPDV.isPagou()) {
//                this.salvarVenda();
//            } else {
//                JOptionPane.showMessageDialog(rootPane, "Você cancelou o pagamento!", "ATENÇÃO!", JOptionPane.WARNING_MESSAGE);
//            }
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(rootPane, "Erro ao cancelar o pagamento!", "ATENÇÃO!", JOptionPane.WARNING_MESSAGE);
//        }

    }//GEN-LAST:event_jMt_ComFinalizarVendaActionPerformed

    
//    /**
//     * Efetuar a limpeza da tela após terminar a venda.
//     */
//    private void limparTela(){
//        //limpando campos
//        jFTF_ValorBruto.setText("");
//        //limpando tabela
//        DefaultTableModel modelo = (DefaultTableModel)jTbPDV.getModel();
//        modelo.setNumRows(0);
//        
//        //Status da label no PDV do Caixa
//        jLb_Status.setText("Caixa Livre!");
//        
//    }
//    
//    /**
//     * Salvando vendas
//     */
//    private void salvarVenda(){
//        int cont;
//        int codigoProduto = 0, codigoVenda = 0;
//        modelVendas = new ModelVendas();
//        modelVendas.setCliente(1);
//        try {
//             modelVendas.setVenDataVenda(bLDatas.converterDataParaDateUS(new java.util.Date(System.currentTimeMillis())));
//        } catch (Exception ex) {
//        }
//        //adicionando
//        modelVendas.setVenValorBruto(Double.parseDouble(jFTF_ValorBruto.getText()));
//        modelVendas.setVenDesconto(viewPagamentoPDV.getDesconto());
//        modelVendas.setVenValorLiquido(blMascara.arredondamentoComPontoDuasCasas(viewPagamentoPDV.getValorTotal()));
//        //Salvando no banco a venda
//        codigoVenda = controllerVendas.salvarVendasController(modelVendas);
//
//        //SALVANDO PRODUTOS
//        cont = jTbPDV.getRowCount();
//        for (int i = 0; i < cont; i++) {
//            //salvando os produto no estoque vendas dos produtos
//            codigoProduto = (int)jTbPDV.getValueAt(i, 1);
//            modelVendasProdutos = new ModelVendasProdutos();
//            modelProdutos = new ModelProdutos();
//            //adicionando venda produto
//            modelVendasProdutos.setProduto(codigoProduto);
//            modelVendasProdutos.setVendas(codigoVenda);
//            modelVendasProdutos.setVenProValor((double)jTbPDV.getValueAt(i, 4));
//            modelVendasProdutos.setVenProQuantidade(Integer.parseInt(jTbPDV.getValueAt(i, 3).toString()));
//
//            //produto, dando baixa no estoque de vendas dos produtos
//            modelProdutos.setIdProduto(codigoProduto);
//            //retornando estoque atual e dando baixa
//            modelProdutos.setProEstoque(controllerProdutos.retornarProdutoController(codigoProduto).getProEstoque() 
//            - Integer.parseInt(jTbPDV.getValueAt(i, 3).toString()));
//
//            //Adicinando
//            listaModelVendasProdutos.add(modelVendasProdutos); 
//            listaModelProdutos.add(modelProdutos);
//        }
//        //Salvar os produtos da venda
//        if(controllerVendasProdutos.salvarVendasProdutosController(listaModelVendasProdutos)){
//            //alterar o estoque de produtos
//            controllerProdutos.alterarEstoqueProdutoController(listaModelProdutos);
//            //JOptionPane.showMessageDialog(rootPane, "produtos da venda salvo com sucesso!", "ATENÇÃO!", JOptionPane.WARNING_MESSAGE);
//            //Retornando para 1 depois da soma.
//            this.limparTela();
//            
//        }else{
//            JOptionPane.showMessageDialog(rootPane, "Erro ao salva produto da venda!", "ERRO:", JOptionPane.ERROR_MESSAGE);
//        }
//    }
//    
//    /**
//     * Pegando conteudos e add o produto
//     * @param e 
//     */
//    private void pegarConteudo(java.awt.event.KeyEvent e){
//        //Status da label no PDV do Caixa
//        jLb_Status.setText("Venda em aberta!");
//        
//        DefaultTableModel modelo = (DefaultTableModel)jTbPDV.getModel();
//        if(e.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){
//            try {
//                modelProdutos = controllerProdutos.retornarProdutoController(Integer.parseInt(jTF_COD_Prod.getText()));
//                modelo.addRow(new Object[]{
//                    modelo.getRowCount() + 1,
//                    modelProdutos.getIdProduto(),
//                    modelProdutos.getProNome(),
//                    QUANTIDADE,
//                    modelProdutos.getProValor(),
//                    //Multiplicação
//                    modelProdutos.getProValor() * QUANTIDADE
//                });
//                //Passando o valor para campos de TEXTO na tela 
//                //poder ser feito o tratamento de String null de 
//                //duas formas String.valueOf ou concartenar com aspas dupla (+ "") no final
//                //jFTF_ValorTotal.setText(somaValorTotal() + "");
//                jFTF_ValorBruto.setText(String.valueOf(somaValorTotal()));
//                //limpando o campo
//                jTF_COD_Prod.setText("");
//                QUANTIDADE = 1;
//            } catch (Exception ex) {
//                JOptionPane.showMessageDialog(rootPane, "Você deve informar apena numero!", "ERRR:", JOptionPane.ERROR_MESSAGE);
//            }
//        }
//    }
//    /**
//     * calculo de somas dos Itens
//     * @return soma 
//     */
//    private float somaValorTotal(){
//        float soma = 0, valor = 0;
//        int cont = jTbPDV.getRowCount();
//        for (int i = 0; i < cont; i++) {
//            valor = Float.parseFloat(String.valueOf(jTbPDV.getValueAt(i, 5)));
//            soma += valor;
//        }
//        return soma;
//    }
//    /**
//     * Setandor o Operador do Caixa pelo nome na Tela pela jLb 
//     */
//    private void setarOperador(){
//        jLb_Operador.setText(modelSessaoUsuario.nome);
//    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewTestePDV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewTestePDV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewTestePDV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewTestePDV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewTestePDV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBExcluir;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JFormattedTextField jFTFCodBarras;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JFormattedTextField jFormattedTextField3;
    private javax.swing.JFormattedTextField jFormattedTextField4;
    private javax.swing.JFormattedTextField jFormattedTextField5;
    private javax.swing.JFormattedTextField jFormattedTextField6;
    private javax.swing.JFormattedTextField jFormattedTextField7;
    private javax.swing.JFormattedTextField jFormattedTextField8;
    private javax.swing.JFormattedTextField jFormattedTextField9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLb_Caixa;
    private javax.swing.JLabel jLb_Operador;
    private javax.swing.JLabel jLb_Status;
    private javax.swing.JMenuItem jMI_ComAlteraQtdProd;
    private javax.swing.JMenuItem jMI_ComPesqProd;
    private javax.swing.JMenuItem jMI_ExcluirProduto;
    private javax.swing.JMenuItem jMI_Sair;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMt_ComFinalizarVenda;
    private javax.swing.JPanel jPanelCALCULO;
    private javax.swing.JPanel jPanelCOD_BARRAS;
    private javax.swing.JPanel jPanelCaixa;
    private javax.swing.JPanel jPanelTENS_ADD;
    private javax.swing.JPanel jPanelTeste;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTB_ITENS;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
