/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControllerUsuario;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ModelUsuario;

/**
 *
 * @author Mr-Robot
 */
public class ViewUsuario extends javax.swing.JFrame {

    
    ControllerUsuario controllerUsuario = new ControllerUsuario();
    ModelUsuario modelUsuario = new ModelUsuario();
    ArrayList<ModelUsuario> listaModelUsuarios = new ArrayList<>();
    
    String salvarAlterar;
    
    /**
     * Creates new form ViewUsuario
     */
    public ViewUsuario() {
        initComponents();
        this.carregarUsuario();
        this.limparCampos();
        this.habilitarDesabilitarCampos(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_usuCod = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_usuNome = new javax.swing.JTextField();
        txt_usuLogin = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPassF_usuSenha = new javax.swing.JPasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_Usuario = new javax.swing.JTable();
        jB_novo = new javax.swing.JButton();
        jB_salvar = new javax.swing.JButton();
        jB_alterar = new javax.swing.JButton();
        jB_excluir = new javax.swing.JButton();
        jB_cancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Usuários e Consultas");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Código:");

        jLabel3.setText("Nome:");

        txt_usuCod.setEditable(false);
        txt_usuCod.setEnabled(false);

        jLabel4.setText("Login:");

        jLabel5.setText("Senha:");

        tb_Usuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Login"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tb_Usuario);
        if (tb_Usuario.getColumnModel().getColumnCount() > 0) {
            tb_Usuario.getColumnModel().getColumn(0).setMinWidth(50);
            tb_Usuario.getColumnModel().getColumn(0).setPreferredWidth(50);
            tb_Usuario.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        jB_novo.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jB_novo.setText("Novo");
        jB_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_novoActionPerformed(evt);
            }
        });

        jB_salvar.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jB_salvar.setText("Salvar");
        jB_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_salvarActionPerformed(evt);
            }
        });

        jB_alterar.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jB_alterar.setText("Alterar");
        jB_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_alterarActionPerformed(evt);
            }
        });

        jB_excluir.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jB_excluir.setText("Excluir");
        jB_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_excluirActionPerformed(evt);
            }
        });

        jB_cancelar.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jB_cancelar.setText("Apagar");
        jB_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_usuCod, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_usuNome, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(204, 204, 204)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_usuLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPassF_usuSenha))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jB_novo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jB_salvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jB_alterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jB_excluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jB_cancelar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_usuCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_usuNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_usuLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPassF_usuSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_novo)
                    .addComponent(jB_salvar)
                    .addComponent(jB_alterar)
                    .addComponent(jB_excluir)
                    .addComponent(jB_cancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Usuários");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(506, 534));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jB_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_novoActionPerformed
        this.habilitarDesabilitarCampos(true);
        this.limparCampos();
        salvarAlterar = "salvar";
    }//GEN-LAST:event_jB_novoActionPerformed

    private void jB_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_salvarActionPerformed
        
        try {
            modelUsuario.setIdUsuario(Integer.parseInt(txt_usuCod.getText()));
        } catch (NumberFormatException e) {
            //JOptionPane.showMessageDialog(rootPane, "Erro ao no código!", "ERRO:", JOptionPane.ERROR_MESSAGE);
           //e.printStackTrace();
        }
        
        modelUsuario.setUsuNome(txt_usuNome.getText());
        modelUsuario.setUsuLogin(txt_usuLogin.getText());
        modelUsuario.setUsuSenha(jPassF_usuSenha.getText());
        
        if(salvarAlterar.equals("salvar")){
            
            if(controllerUsuario.salvarUsuarioController(modelUsuario) > 0){
                JOptionPane.showMessageDialog(rootPane, "Usuário cadastrado com sucesso!", "ATENÇÃO!", JOptionPane.WARNING_MESSAGE);
                
                this.carregarUsuario();
                this.habilitarDesabilitarCampos(false);
                this.limparCampos();
                
            }else{
                JOptionPane.showMessageDialog(rootPane, "Erro ao cadastrar Usuário!", "ERRO:", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            
            if(controllerUsuario.atualizarUsuarioController(modelUsuario)){
                JOptionPane.showMessageDialog(rootPane, "Usuário atualizado com sucesso!", "ATENÇÃO!", JOptionPane.WARNING_MESSAGE);
                
                this.carregarUsuario();
                this.habilitarDesabilitarCampos(false);
                this.limparCampos();
                
            }else{
                JOptionPane.showMessageDialog(rootPane, "Erro ao atualizar Usuário!", "ERRO:", JOptionPane.ERROR_MESSAGE);
            }
        }
    
    }//GEN-LAST:event_jB_salvarActionPerformed

    private void jB_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_alterarActionPerformed
        salvarAlterar = "alterar";
        int linha = this.tb_Usuario.getSelectedRow();
        try {
            int codigoUsuario = (int) this.tb_Usuario.getValueAt(linha, 0);
            //Recuperar dados do banco
            modelUsuario = controllerUsuario.getUsuarioController(codigoUsuario);
            //Setar na interface
            txt_usuCod.setText(String.valueOf(modelUsuario.getIdUsuario()));
            txt_usuNome.setText(modelUsuario.getUsuNome());
            txt_usuLogin.setText(modelUsuario.getUsuLogin());
            jPassF_usuSenha.setText(modelUsuario.getUsuSenha());
            
            this.habilitarDesabilitarCampos(true);
            this.limparCampos();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Código inválido ou nenhum registro selecionado.", "AVISO!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jB_alterarActionPerformed

    private void jB_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_excluirActionPerformed
        //selecionar a linha
        int linha = tb_Usuario.getSelectedRow();
        //pegando o codigo da coluna da linha selecionada
        int codigoUsuario = (int) tb_Usuario.getValueAt(linha, 0);
        
        if(controllerUsuario.excluirUsuarioController(codigoUsuario)){
           JOptionPane.showMessageDialog(rootPane, "Usuário excluído com sucesso!", "ATENÇÃO!", JOptionPane.WARNING_MESSAGE);
            this.carregarUsuario();
            this.habilitarDesabilitarCampos(false);
            this.limparCampos();
        }else{
            JOptionPane.showMessageDialog(rootPane, "Erro ao excluir Usuário!", "ERRO:", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jB_excluirActionPerformed

    private void jB_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_cancelarActionPerformed
        this.habilitarDesabilitarCampos(false);
        this.limparCampos();
    }//GEN-LAST:event_jB_cancelarActionPerformed
    /**
     * limpar formulário usuário
     */
    private void limparCampos(){
        txt_usuCod.setText("");
        txt_usuNome.setText("");
        txt_usuLogin.setText("");
        jPassF_usuSenha.setText("");
    }
    
    /**
     * habilitar e desabilitar campos e botoes do formulario
     * @param condicao 
     */
    private void habilitarDesabilitarCampos(boolean condicao){
        txt_usuNome.setEnabled(condicao);
        txt_usuLogin.setEnabled(condicao);
        jPassF_usuSenha.setEnabled(condicao);
        jB_salvar.setEnabled(condicao);
        jB_excluir.setEnabled(condicao);
        jB_cancelar.setEnabled(condicao);
    }
    /**
     * carregar usuários na tabela
     */
    private void carregarUsuario(){
        listaModelUsuarios = controllerUsuario.getListaUsuarioController();
        //Usando o modelo padrão de tabela
        DefaultTableModel modelo = (DefaultTableModel)tb_Usuario.getModel();
        //zerando linha 0 e setando os dados
        modelo.setNumRows(0);
        //inserir produtos na tabela
        int cont = listaModelUsuarios.size();
        //contador de tamanho da lista
        for (int i = 0; i < cont; i++) {
            //preenchendo col. e linha.
            modelo.addRow(new Object[]{
                listaModelUsuarios.get(i).getIdUsuario(),
                listaModelUsuarios.get(i).getUsuNome(),
                listaModelUsuarios.get(i).getUsuLogin(),
            });
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_alterar;
    private javax.swing.JButton jB_cancelar;
    private javax.swing.JButton jB_excluir;
    private javax.swing.JButton jB_novo;
    private javax.swing.JButton jB_salvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPassF_usuSenha;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_Usuario;
    private javax.swing.JTextField txt_usuCod;
    private javax.swing.JTextField txt_usuLogin;
    private javax.swing.JTextField txt_usuNome;
    // End of variables declaration//GEN-END:variables
}
