/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JFrame;
import util.BLDatas;
import util.FundoTela;

/**
 *
 * @author Mr-Robot
 */
public class ViewMenuPrincipal extends javax.swing.JFrame {

    BLDatas blDatas = new BLDatas();
    
    // Metodo
    FundoTela tela;
    /**
     * Creates new form ViewMenuPrincipal
     */
    public ViewMenuPrincipal() {
        initComponents();
        //Maximinizando Tela principal
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        //        //hora
//        Timer timer = new Timer(1000, new hora());
//        timer.start();
        jlData.setText(blDatas.retornarDataHora());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        uJPanelImagem1 = new componentes.UJPanelImagem();
        jPanel1 = new javax.swing.JPanel();
        jB_Clientes = new javax.swing.JButton();
        jB_Produtos = new javax.swing.JButton();
        jB_Usuario = new javax.swing.JButton();
        jB_Vendas = new javax.swing.JButton();
        jB_PDV = new javax.swing.JButton();
        jB_PdvTeste = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jlUsuario = new javax.swing.JLabel();
        jlData = new javax.swing.JLabel();
        jMBar_Principal = new javax.swing.JMenuBar();
        jMenuArquivo = new javax.swing.JMenu();
        jMI_Sair = new javax.swing.JMenuItem();
        jMenuCadastro = new javax.swing.JMenu();
        jMI_Clientes = new javax.swing.JMenuItem();
        jMI_Produtos = new javax.swing.JMenuItem();
        jMI_Usuarios = new javax.swing.JMenuItem();
        jM_Vendas = new javax.swing.JMenu();
        jMI_Vendas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela de Menu Principal");
        setResizable(false);

        uJPanelImagem1.setImagem(new java.io.File("F:\\IDE de Programas\\NetBeans\\VendasBL\\src\\imagens\\tela_pincipal.png"));

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Menu", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 51, 153))); // NOI18N

        jB_Clientes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jB_Clientes.setText("Clientes");
        jB_Clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_ClientesActionPerformed(evt);
            }
        });

        jB_Produtos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jB_Produtos.setText("Produtos");
        jB_Produtos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_ProdutosActionPerformed(evt);
            }
        });

        jB_Usuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jB_Usuario.setText("Usuários");
        jB_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_UsuarioActionPerformed(evt);
            }
        });

        jB_Vendas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jB_Vendas.setText("Vendas");
        jB_Vendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_VendasActionPerformed(evt);
            }
        });

        jB_PDV.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jB_PDV.setText("PDV");
        jB_PDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_PDVActionPerformed(evt);
            }
        });

        jB_PdvTeste.setText("PDV-Teste");
        jB_PdvTeste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_PdvTesteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jB_Clientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jB_Produtos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jB_Usuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jB_Vendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jB_PDV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jB_PdvTeste)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jB_Clientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jB_Produtos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jB_Vendas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jB_Usuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jB_PDV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jB_PdvTeste)
                .addContainerGap(172, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Logado:");

        jlUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jlUsuario.setText("usuario");

        jlData.setForeground(new java.awt.Color(255, 255, 255));
        jlData.setText("Data/Hora");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 525, Short.MAX_VALUE)
                .addComponent(jlData, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jlUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout uJPanelImagem1Layout = new javax.swing.GroupLayout(uJPanelImagem1);
        uJPanelImagem1.setLayout(uJPanelImagem1Layout);
        uJPanelImagem1Layout.setHorizontalGroup(
            uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(uJPanelImagem1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        uJPanelImagem1Layout.setVerticalGroup(
            uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, uJPanelImagem1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(23, 23, 23)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMenuArquivo.setBackground(new java.awt.Color(255, 255, 255));
        jMenuArquivo.setForeground(new java.awt.Color(0, 153, 153));
        jMenuArquivo.setText("Arquivos");
        jMenuArquivo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jMI_Sair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMI_Sair.setText("Sair");
        jMI_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMI_SairActionPerformed(evt);
            }
        });
        jMenuArquivo.add(jMI_Sair);

        jMBar_Principal.add(jMenuArquivo);

        jMenuCadastro.setBackground(new java.awt.Color(255, 255, 255));
        jMenuCadastro.setForeground(new java.awt.Color(0, 153, 153));
        jMenuCadastro.setText("Cadastros");
        jMenuCadastro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jMI_Clientes.setText("Clientes");
        jMI_Clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMI_ClientesActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMI_Clientes);

        jMI_Produtos.setText("Produtos");
        jMI_Produtos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMI_ProdutosActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMI_Produtos);

        jMI_Usuarios.setText("Usuários");
        jMI_Usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMI_UsuariosActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMI_Usuarios);

        jMBar_Principal.add(jMenuCadastro);

        jM_Vendas.setBackground(new java.awt.Color(255, 255, 255));
        jM_Vendas.setForeground(new java.awt.Color(0, 153, 153));
        jM_Vendas.setText("Vendas");
        jM_Vendas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jM_Vendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jM_VendasActionPerformed(evt);
            }
        });

        jMI_Vendas.setText("Vendas");
        jMI_Vendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMI_VendasActionPerformed(evt);
            }
        });
        jM_Vendas.add(jMI_Vendas);

        jMBar_Principal.add(jM_Vendas);

        setJMenuBar(jMBar_Principal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(uJPanelImagem1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(uJPanelImagem1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB_ClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_ClientesActionPerformed
        // TODO add your handling code here:
        new ViewCliente().setVisible(true);
    }//GEN-LAST:event_jB_ClientesActionPerformed

    private void jB_ProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_ProdutosActionPerformed
        // TODO add your handling code here:
        new ViewProduto().setVisible(true);
    }//GEN-LAST:event_jB_ProdutosActionPerformed

    private void jB_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_UsuarioActionPerformed
        // TODO add your handling code here:
        new ViewUsuario().setVisible(true);
    }//GEN-LAST:event_jB_UsuarioActionPerformed

    private void jB_VendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_VendasActionPerformed
        // TODO add your handling code here:
        new ViewVendas().setVisible(true);
    }//GEN-LAST:event_jB_VendasActionPerformed

    private void jB_PDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_PDVActionPerformed
        // TODO add your handling code here:
        new ViewPDV().setVisible(true);
    }//GEN-LAST:event_jB_PDVActionPerformed

    private void jMI_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMI_SairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMI_SairActionPerformed

    private void jMI_ClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMI_ClientesActionPerformed
        // TODO add your handling code here:
        new ViewCliente().setVisible(true);
    }//GEN-LAST:event_jMI_ClientesActionPerformed

    private void jMI_ProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMI_ProdutosActionPerformed
        // TODO add your handling code here:
        new ViewProduto().setVisible(true);
    }//GEN-LAST:event_jMI_ProdutosActionPerformed

    private void jMI_UsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMI_UsuariosActionPerformed
        // TODO add your handling code here:
        new ViewUsuario().setVisible(true);
    }//GEN-LAST:event_jMI_UsuariosActionPerformed

    private void jMI_VendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMI_VendasActionPerformed
        // TODO add your handling code here:
        new ViewVendas().setVisible(true);
    }//GEN-LAST:event_jMI_VendasActionPerformed

    private void jM_VendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jM_VendasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jM_VendasActionPerformed

    private void jB_PdvTesteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_PdvTesteActionPerformed
        // TODO add your handling code here:
        new ViewTestePDV().setVisible(true);
    }//GEN-LAST:event_jB_PdvTesteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_Clientes;
    private javax.swing.JButton jB_PDV;
    private javax.swing.JButton jB_PdvTeste;
    private javax.swing.JButton jB_Produtos;
    private javax.swing.JButton jB_Usuario;
    private javax.swing.JButton jB_Vendas;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMBar_Principal;
    private javax.swing.JMenuItem jMI_Clientes;
    private javax.swing.JMenuItem jMI_Produtos;
    private javax.swing.JMenuItem jMI_Sair;
    private javax.swing.JMenuItem jMI_Usuarios;
    private javax.swing.JMenuItem jMI_Vendas;
    private javax.swing.JMenu jM_Vendas;
    private javax.swing.JMenu jMenuArquivo;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel jlData;
    private javax.swing.JLabel jlUsuario;
    private componentes.UJPanelImagem uJPanelImagem1;
    // End of variables declaration//GEN-END:variables

    




}
