/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControllerProdutos;
import controller.ControllerVendas;
import controller.ControllerVendasProdutos;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ModelProdutos;
import model.ModelSessaoUsuario;
import model.ModelVendas;
import model.ModelVendasProdutos;
import util.BLDatas;
import util.BLMascaras;

/**
 *
 * @author Mr-Robot
 */
public class ViewPDV extends javax.swing.JFrame {
    //Instanciando o Conversor de datas
    BLDatas bLDatas = new BLDatas();
    
    ControllerProdutos controllerProdutos = new ControllerProdutos();
    ModelProdutos modelProdutos = new ModelProdutos();
    ModelVendas modelVendas = new ModelVendas();
    ModelVendasProdutos modelVendasProdutos = new ModelVendasProdutos();
    ArrayList<ModelVendasProdutos> listaModelVendasProdutos = new ArrayList<>();
    ArrayList<ModelProdutos> listaModelProdutos = new ArrayList<>();
    ControllerVendas controllerVendas = new ControllerVendas();
    ControllerVendasProdutos controllerVendasProdutos = new ControllerVendasProdutos();
    ModelSessaoUsuario modelSessaoUsuario = new ModelSessaoUsuario();
    
    BLMascaras blMascara = new BLMascaras();
    
    //Instanciando Tela de pagamento PDV
    private ViewPagamentoPDV viewPagamentoPDV;
    
    int QUANTIDADE;
    
    /**
     * Creates new form ViewPDV
     */
    public ViewPDV() {
        initComponents();
        
        //Chamando metodos globais
        setLocationRelativeTo(null);
        //padrão a quantidade
        QUANTIDADE = 1;
        setarOperador();
        
        //Chamando  a TELA PAGAMENTO
        //this.viewPagamentoPDV = new ViewPagamentoPDV(this, true);
        this.limparTela();
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelLogoMarca = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelSubMenu = new javax.swing.JPanel();
        jPanelCaixa = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLb_Caixa = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLb_Operador = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLb_Status = new javax.swing.JLabel();
        jPanelComandos = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jFTF_ValorBruto = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanelTabelas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTbPDV = new javax.swing.JTable();
        jTF_COD_Prod = new javax.swing.JFormattedTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMI_Sair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMI_ExcluirProduto = new javax.swing.JMenuItem();
        jMI_ComAlteraQtdProd = new javax.swing.JMenuItem();
        jMt_ComFinalizarVenda = new javax.swing.JMenuItem();
        jMI_ComPesqProd = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela de Caixa PDV");

        jPanelLogoMarca.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 0));
        jLabel1.setText("ISsoftware-LOGO");

        javax.swing.GroupLayout jPanelLogoMarcaLayout = new javax.swing.GroupLayout(jPanelLogoMarca);
        jPanelLogoMarca.setLayout(jPanelLogoMarcaLayout);
        jPanelLogoMarcaLayout.setHorizontalGroup(
            jPanelLogoMarcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLogoMarcaLayout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelLogoMarcaLayout.setVerticalGroup(
            jPanelLogoMarcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLogoMarcaLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jPanelSubMenu.setBackground(new java.awt.Color(204, 255, 204));

        jPanelCaixa.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Caixa:");

        jLb_Caixa.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLb_Caixa.setText("Caixa");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Operador:");

        jLb_Operador.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLb_Operador.setText("Operador");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("Status:");

        jLb_Status.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLb_Status.setText("Status");

        javax.swing.GroupLayout jPanelCaixaLayout = new javax.swing.GroupLayout(jPanelCaixa);
        jPanelCaixa.setLayout(jPanelCaixaLayout);
        jPanelCaixaLayout.setHorizontalGroup(
            jPanelCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCaixaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLb_Operador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelCaixaLayout.createSequentialGroup()
                        .addGroup(jPanelCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLb_Status, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLb_Caixa, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelCaixaLayout.setVerticalGroup(
            jPanelCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCaixaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLb_Caixa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLb_Operador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLb_Status))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelComandos.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setText("Valor Bruto");

        jFTF_ValorBruto.setEditable(false);
        jFTF_ValorBruto.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setText("Comandos");

        jLabel7.setText("F3 - Quantidade");

        jLabel8.setText("F4 - Finalizar Venda");

        jLabel9.setText("F5 - Pesquisar Produto");

        jLabel10.setText("F6 - Sair do PDV");

        jLabel11.setText("F2 - Excluir");

        jLabel12.setText("Ctrl + Alt + E - Fechar todo o Sistema");

        javax.swing.GroupLayout jPanelComandosLayout = new javax.swing.GroupLayout(jPanelComandos);
        jPanelComandos.setLayout(jPanelComandosLayout);
        jPanelComandosLayout.setHorizontalGroup(
            jPanelComandosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelComandosLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jFTF_ValorBruto)
                .addContainerGap())
            .addGroup(jPanelComandosLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel5)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanelComandosLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanelComandosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(jPanelComandosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelComandosLayout.createSequentialGroup()
                            .addGroup(jPanelComandosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9)
                                .addComponent(jLabel10))
                            .addGap(46, 46, 46))
                        .addGroup(jPanelComandosLayout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelComandosLayout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        jPanelComandosLayout.setVerticalGroup(
            jPanelComandosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelComandosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFTF_ValorBruto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(17, 17, 17)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addContainerGap(157, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelSubMenuLayout = new javax.swing.GroupLayout(jPanelSubMenu);
        jPanelSubMenu.setLayout(jPanelSubMenuLayout);
        jPanelSubMenuLayout.setHorizontalGroup(
            jPanelSubMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSubMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSubMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelCaixa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelSubMenuLayout.createSequentialGroup()
                        .addComponent(jPanelComandos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelSubMenuLayout.setVerticalGroup(
            jPanelSubMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSubMenuLayout.createSequentialGroup()
                .addComponent(jPanelCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jPanelComandos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelTabelas.setBackground(new java.awt.Color(204, 204, 255));

        jTbPDV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Código", "Nome", "Quantidade", "Valor Unit.", "Valor Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTbPDV);
        if (jTbPDV.getColumnModel().getColumnCount() > 0) {
            jTbPDV.getColumnModel().getColumn(0).setMinWidth(40);
            jTbPDV.getColumnModel().getColumn(0).setPreferredWidth(40);
            jTbPDV.getColumnModel().getColumn(0).setMaxWidth(40);
            jTbPDV.getColumnModel().getColumn(1).setMinWidth(50);
            jTbPDV.getColumnModel().getColumn(1).setPreferredWidth(50);
            jTbPDV.getColumnModel().getColumn(1).setMaxWidth(50);
            jTbPDV.getColumnModel().getColumn(3).setMinWidth(70);
            jTbPDV.getColumnModel().getColumn(3).setPreferredWidth(70);
            jTbPDV.getColumnModel().getColumn(3).setMaxWidth(70);
            jTbPDV.getColumnModel().getColumn(4).setMinWidth(80);
            jTbPDV.getColumnModel().getColumn(4).setPreferredWidth(80);
            jTbPDV.getColumnModel().getColumn(4).setMaxWidth(80);
            jTbPDV.getColumnModel().getColumn(5).setMinWidth(90);
            jTbPDV.getColumnModel().getColumn(5).setPreferredWidth(90);
            jTbPDV.getColumnModel().getColumn(5).setMaxWidth(90);
        }

        jTF_COD_Prod.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jTF_COD_Prod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTF_COD_ProdKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTF_COD_ProdKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanelTabelasLayout = new javax.swing.GroupLayout(jPanelTabelas);
        jPanelTabelas.setLayout(jPanelTabelasLayout);
        jPanelTabelasLayout.setHorizontalGroup(
            jPanelTabelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTabelasLayout.createSequentialGroup()
                .addGroup(jPanelTabelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTF_COD_Prod, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 707, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );
        jPanelTabelasLayout.setVerticalGroup(
            jPanelTabelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTabelasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTF_COD_Prod, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenu1.setText("Arquivos");

        jMI_Sair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        jMI_Sair.setText("Sair");
        jMI_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMI_SairActionPerformed(evt);
            }
        });
        jMenu1.add(jMI_Sair);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Comandos");

        jMI_ExcluirProduto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        jMI_ExcluirProduto.setText("Excluir Produtos");
        jMI_ExcluirProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMI_ExcluirProdutoActionPerformed(evt);
            }
        });
        jMenu2.add(jMI_ExcluirProduto);

        jMI_ComAlteraQtdProd.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        jMI_ComAlteraQtdProd.setText("Alterar quantidade");
        jMI_ComAlteraQtdProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMI_ComAlteraQtdProdActionPerformed(evt);
            }
        });
        jMenu2.add(jMI_ComAlteraQtdProd);

        jMt_ComFinalizarVenda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        jMt_ComFinalizarVenda.setText("Finalizar Venda");
        jMt_ComFinalizarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMt_ComFinalizarVendaActionPerformed(evt);
            }
        });
        jMenu2.add(jMt_ComFinalizarVenda);

        jMI_ComPesqProd.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        jMI_ComPesqProd.setText("Pesquisar Produtos");
        jMenu2.add(jMI_ComPesqProd);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelTabelas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelLogoMarca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelSubMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelLogoMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelTabelas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanelSubMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMt_ComFinalizarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMt_ComFinalizarVendaActionPerformed
        try {
            this.viewPagamentoPDV = new ViewPagamentoPDV(this, true);
            //Pegando o valor Total
            viewPagamentoPDV.setValorTotal(Float.parseFloat(jFTF_ValorBruto.getText()));
            //Setando no metodos da viewPagamentoPDV e jogando o valor na view
            viewPagamentoPDV.setFormatedTextFielValorTotal();
            //Mostrando Tela PagamentoPDV 
            viewPagamentoPDV.setVisible(true);

            System.out.println(viewPagamentoPDV.getFormaPagamento());

            if (viewPagamentoPDV.isPagou()) {
                this.salvarVenda();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Você cancelou o pagamento!", "ATENÇÃO!", JOptionPane.WARNING_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao cancelar o pagamento!", "ATENÇÃO!", JOptionPane.WARNING_MESSAGE);
        }
        
        
    }//GEN-LAST:event_jMt_ComFinalizarVendaActionPerformed

    private void jMI_ComAlteraQtdProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMI_ComAlteraQtdProdActionPerformed
        // TODO add your handling code here:
        //setando a quantidade para somatório
        QUANTIDADE = Integer.parseInt(JOptionPane.showInputDialog("Informe a quantidade!"));
    }//GEN-LAST:event_jMI_ComAlteraQtdProdActionPerformed

    private void jMI_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMI_SairActionPerformed
        dispose();
    }//GEN-LAST:event_jMI_SairActionPerformed

    private void jMI_ExcluirProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMI_ExcluirProdutoActionPerformed
        //ordenando linha depois das exclusões
        int quantLinha = jTbPDV.getRowCount();
        //comparação ser tem itens na lista  
        if (quantLinha < 1) {
            JOptionPane.showMessageDialog(rootPane, "Não existe itens para excluir!", "ATENÇÃO!", JOptionPane.WARNING_MESSAGE);
        } else { // Caso tenha excluar
            DefaultTableModel modelo = (DefaultTableModel)jTbPDV.getModel();
            //Pegando a linha para excluir
            int linha = Integer.parseInt(JOptionPane.showInputDialog("Informe o item que deseja excluir! "));
            // removendo uma linha
            modelo.removeRow(linha-1);
            //somando item restantes
            jFTF_ValorBruto.setText(String.valueOf(somaValorTotal()));

            for (int i = 0; i < quantLinha; i++) {
                modelo.setValueAt(i + 1, i, 0);
            }
        }   
    }//GEN-LAST:event_jMI_ExcluirProdutoActionPerformed

    private void jTF_COD_ProdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTF_COD_ProdKeyReleased
        
    }//GEN-LAST:event_jTF_COD_ProdKeyReleased

    private void jTF_COD_ProdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTF_COD_ProdKeyPressed
        pegarConteudo(evt);
    }//GEN-LAST:event_jTF_COD_ProdKeyPressed

    /**
     * Efetuar a limpeza da tela após terminar a venda.
     */
    private void limparTela(){
        //limpando campos
        jFTF_ValorBruto.setText("");
        //limpando tabela
        DefaultTableModel modelo = (DefaultTableModel)jTbPDV.getModel();
        modelo.setNumRows(0);
        
        //Status da label no PDV do Caixa
        jLb_Status.setText("Caixa Livre!");
        
    }
    
    /**
     * Salvando vendas
     */
    private void salvarVenda(){
        int cont;
        int codigoProduto = 0, codigoVenda = 0;
        modelVendas = new ModelVendas();
        modelVendas.setCliente(1);
        try {
             modelVendas.setVenDataVenda(bLDatas.converterDataParaDateUS(new java.util.Date(System.currentTimeMillis())));
        } catch (Exception ex) {
        }
        //adicionando
        modelVendas.setVenValorBruto(Double.parseDouble(jFTF_ValorBruto.getText()));
        modelVendas.setVenDesconto(viewPagamentoPDV.getDesconto());
        modelVendas.setVenValorLiquido(blMascara.arredondamentoComPontoDuasCasas(viewPagamentoPDV.getValorTotal()));
        //Salvando no banco a venda
        codigoVenda = controllerVendas.salvarVendasController(modelVendas);

        //SALVANDO PRODUTOS
        cont = jTbPDV.getRowCount();
        for (int i = 0; i < cont; i++) {
            //salvando os produto no estoque vendas dos produtos
            codigoProduto = (int)jTbPDV.getValueAt(i, 1);
            modelVendasProdutos = new ModelVendasProdutos();
            modelProdutos = new ModelProdutos();
            //adicionando venda produto
            modelVendasProdutos.setProduto(codigoProduto);
            modelVendasProdutos.setVendas(codigoVenda);
            modelVendasProdutos.setVenProValor((double)jTbPDV.getValueAt(i, 4));
            modelVendasProdutos.setVenProQuantidade(Integer.parseInt(jTbPDV.getValueAt(i, 3).toString()));

            //produto, dando baixa no estoque de vendas dos produtos
            modelProdutos.setIdProduto(codigoProduto);
            //retornando estoque atual e dando baixa
            modelProdutos.setProEstoque(controllerProdutos.retornarProdutoController(codigoProduto).getProEstoque() 
            - Integer.parseInt(jTbPDV.getValueAt(i, 3).toString()));

            //Adicinando
            listaModelVendasProdutos.add(modelVendasProdutos); 
            listaModelProdutos.add(modelProdutos);
        }
        //Salvar os produtos da venda
        if(controllerVendasProdutos.salvarVendasProdutosController(listaModelVendasProdutos)){
            //alterar o estoque de produtos
            controllerProdutos.alterarEstoqueProdutoController(listaModelProdutos);
            //JOptionPane.showMessageDialog(rootPane, "produtos da venda salvo com sucesso!", "ATENÇÃO!", JOptionPane.WARNING_MESSAGE);
            //Retornando para 1 depois da soma.
            this.limparTela();
            
        }else{
            JOptionPane.showMessageDialog(rootPane, "Erro ao salva produto da venda!", "ERRO:", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * Pegando conteudos e add o produto
     * @param e 
     */
    private void pegarConteudo(java.awt.event.KeyEvent e){
        //Status da label no PDV do Caixa
        jLb_Status.setText("Venda em aberta!");
        
        DefaultTableModel modelo = (DefaultTableModel)jTbPDV.getModel();
        if(e.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){
            try {
                modelProdutos = controllerProdutos.retornarProdutoController(Integer.parseInt(jTF_COD_Prod.getText()));
                modelo.addRow(new Object[]{
                    modelo.getRowCount() + 1,
                    modelProdutos.getIdProduto(),
                    modelProdutos.getProNome(),
                    QUANTIDADE,
                    modelProdutos.getProValor(),
                    //Multiplicação
                    modelProdutos.getProValor() * QUANTIDADE
                });
                //Passando o valor para campos de TEXTO na tela 
                //poder ser feito o tratamento de String null de 
                //duas formas String.valueOf ou concartenar com aspas dupla (+ "") no final
                //jFTF_ValorTotal.setText(somaValorTotal() + "");
                jFTF_ValorBruto.setText(String.valueOf(somaValorTotal()));
                //limpando o campo
                jTF_COD_Prod.setText("");
                QUANTIDADE = 1;
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(rootPane, "Você deve informar apena numero!", "ERRR:", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    /**
     * calculo de somas dos Itens
     * @return soma 
     */
    private float somaValorTotal(){
        float soma = 0, valor = 0;
        int cont = jTbPDV.getRowCount();
        for (int i = 0; i < cont; i++) {
            valor = Float.parseFloat(String.valueOf(jTbPDV.getValueAt(i, 5)));
            soma += valor;
        }
        return soma;
    }
    /**
     * Setandor o Operador do Caixa pelo nome na Tela pela jLb 
     */
    private void setarOperador(){
        jLb_Operador.setText(modelSessaoUsuario.nome);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPDV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPDV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPDV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPDV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewPDV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField jFTF_ValorBruto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLb_Caixa;
    private javax.swing.JLabel jLb_Operador;
    private javax.swing.JLabel jLb_Status;
    private javax.swing.JMenuItem jMI_ComAlteraQtdProd;
    private javax.swing.JMenuItem jMI_ComPesqProd;
    private javax.swing.JMenuItem jMI_ExcluirProduto;
    private javax.swing.JMenuItem jMI_Sair;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMt_ComFinalizarVenda;
    private javax.swing.JPanel jPanelCaixa;
    private javax.swing.JPanel jPanelComandos;
    private javax.swing.JPanel jPanelLogoMarca;
    private javax.swing.JPanel jPanelSubMenu;
    private javax.swing.JPanel jPanelTabelas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JFormattedTextField jTF_COD_Prod;
    private javax.swing.JTable jTbPDV;
    // End of variables declaration//GEN-END:variables
}
