/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControllerCliente;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ModelCliente;

/**
 *
 * @author Mr-Robot
 */
public class ViewCliente extends javax.swing.JFrame {

    ControllerCliente controllerCliente = new ControllerCliente();
    ModelCliente modelCliente = new ModelCliente();
    ArrayList<ModelCliente> listaModelCliente = new ArrayList<>();
    
    //variaveis
    String salvarAlterar;
    /**
     * Creates new form ViewCliente
     */
    public ViewCliente() {
        initComponents();
        carregarCliente();
        //chamando o metodo do campos como false
        this.carregarCliente();
        this.habilitarDesabilitarCampo(false);
        this.limparCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txt_cliZona = new javax.swing.JTextField();
        txt_cliBairro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jFTF_cliTel_celular = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        jFTF_cliTel_fixo = new javax.swing.JFormattedTextField();
        jFT_cliCep = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jCBox_cliEstados = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_cliNome = new javax.swing.JTextField();
        txt_cliCod = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_cliEndereco = new javax.swing.JTextField();
        txt_cliCidade = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_cliente = new javax.swing.JTable();
        btn_novo = new javax.swing.JButton();
        btn_salva = new javax.swing.JButton();
        btn_altera = new javax.swing.JButton();
        btn_excluir = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Clientes e Consultas");
        setResizable(false);

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setText("Clientes");

        jPanel1.setBackground(new java.awt.Color(0, 204, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setText("Zona:");

        txt_cliZona.setToolTipText("Ex: Urbana ou Rural");

        jLabel4.setText("Bairro:");

        jLabel10.setText("Telefone Celular:");

        try {
            jFTF_cliTel_celular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel9.setText("Telefone fixo:");

        try {
            jFTF_cliTel_fixo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jFT_cliCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel8.setText("CEP:");

        jCBox_cliEstados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PB", "MG" }));

        jLabel7.setText("UF:");

        jLabel2.setText("Nome:");

        jLabel1.setText("Código:");

        txt_cliCod.setEditable(false);
        txt_cliCod.setForeground(new java.awt.Color(0, 0, 0));
        txt_cliCod.setEnabled(false);

        jLabel3.setText("Endereço:");

        jLabel6.setText("Cidade:");

        tb_cliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Cidade", "Telefone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tb_cliente);
        if (tb_cliente.getColumnModel().getColumnCount() > 0) {
            tb_cliente.getColumnModel().getColumn(0).setMinWidth(10);
            tb_cliente.getColumnModel().getColumn(0).setPreferredWidth(10);
        }

        btn_novo.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btn_novo.setText("Novo");
        btn_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_novoActionPerformed(evt);
            }
        });

        btn_salva.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btn_salva.setText("Salvar");
        btn_salva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvaActionPerformed(evt);
            }
        });

        btn_altera.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btn_altera.setText("Alterar");
        btn_altera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_alteraActionPerformed(evt);
            }
        });

        btn_excluir.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btn_excluir.setText("Apagar");
        btn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirActionPerformed(evt);
            }
        });

        btn_cancelar.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btn_cancelar.setText("Parar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_novo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_salva)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_altera)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_excluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_cancelar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_cliCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jCBox_cliEstados, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jFTF_cliTel_fixo, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jFTF_cliTel_celular, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(276, 276, 276)
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_cliEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_cliBairro))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_cliCod, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(290, 290, 290)
                                .addComponent(jLabel5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txt_cliNome, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_cliZona, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jFT_cliCep))))
                .addGap(221, 221, 221))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_cliCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_cliNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_cliZona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFT_cliCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_cliEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_cliBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(jLabel9)
                                .addComponent(jLabel10))))
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFTF_cliTel_celular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_cliCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCBox_cliEstados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jFTF_cliTel_fixo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_novo)
                    .addComponent(btn_salva)
                    .addComponent(btn_altera)
                    .addComponent(btn_excluir)
                    .addComponent(btn_cancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(294, 294, 294))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(696, 562));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_salvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvaActionPerformed
        //Atençao Para resolver
        try {
            modelCliente.setIdCliente(Integer.parseInt(this.txt_cliCod.getText()));
        } catch (NumberFormatException e) {
           //JOptionPane.showMessageDialog(rootPane, "Erro ao no código!", "ERRO:", JOptionPane.ERROR_MESSAGE);
           //e.printStackTrace();
        }
        
        modelCliente.setCliNome(this.txt_cliNome.getText());
        modelCliente.setCliZona(this.txt_cliZona.getText());
        modelCliente.setCliEndereco(this.txt_cliEndereco.getText());
        modelCliente.setCliBairro(this.txt_cliBairro.getText());
        modelCliente.setCliCidade(this.txt_cliCidade.getText());
        modelCliente.setCliUf(this.jCBox_cliEstados.getSelectedItem().toString());
        modelCliente.setCliCep(this.jFT_cliCep.getText());
        modelCliente.setCliTelFixo(this.jFTF_cliTel_fixo.getText());
        modelCliente.setCliTelCel(this.jFTF_cliTel_celular.getText());

        if(salvarAlterar.equals("salvar")){
            
            if(controllerCliente.salvarClienteController(modelCliente) > 0){
                JOptionPane.showMessageDialog(rootPane, "Cliente cadastrado com sucesso!", "ATENÇÃO!", JOptionPane.WARNING_MESSAGE);
                this.carregarCliente();
                this.habilitarDesabilitarCampo(false);
                this.limparCampos();
            }else{
                JOptionPane.showMessageDialog(rootPane, "Erro ao cadastrar Cliente!", "ERRO:", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            
            if(controllerCliente.atualizarClienteController(modelCliente)){
                JOptionPane.showMessageDialog(rootPane, "Cliente atualizado com sucesso!", "ATENÇÃO!", JOptionPane.WARNING_MESSAGE);
                
                this.carregarCliente();
                this.habilitarDesabilitarCampo(false);
                this.limparCampos();
                
            }else{
                JOptionPane.showMessageDialog(rootPane, "Erro ao atualizar Cliente!", "ERRO:", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btn_salvaActionPerformed

    private void btn_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_novoActionPerformed
        // TODO add your handling code here:
        this.habilitarDesabilitarCampo(true);
        this.limparCampos();
        salvarAlterar = "salvar";
    }//GEN-LAST:event_btn_novoActionPerformed

    private void btn_alteraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_alteraActionPerformed
        salvarAlterar = "alterar";
        int linha = this.tb_cliente.getSelectedRow();
        try {
            int codigoCliete = (int) this.tb_cliente.getValueAt(linha, 0);
            //Recuperar dados do banco
            modelCliente = controllerCliente.getClienteController(codigoCliete);
            //Setar na interface
            txt_cliCod.setText(String.valueOf(modelCliente.getIdCliente()));
            txt_cliNome.setText(modelCliente.getCliNome());
            txt_cliZona.setText(modelCliente.getCliZona());
            txt_cliEndereco.setText(modelCliente.getCliEndereco());
            txt_cliBairro.setText(modelCliente.getCliBairro());
            txt_cliCidade.setText(modelCliente.getCliCidade());
            jCBox_cliEstados.setSelectedItem(modelCliente.getCliUf());
            jFT_cliCep.setText(modelCliente.getCliCep());
            jFTF_cliTel_fixo.setText(modelCliente.getCliTelFixo());
            jFTF_cliTel_celular.setText(modelCliente.getCliTelCel());
            
            habilitarDesabilitarCampo(true);
            this.limparCampos();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Código inválido ou nenhum registro selecionado.", "AVISO!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_alteraActionPerformed

    private void btn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirActionPerformed
        //selecionar a linha
        int linha = tb_cliente.getSelectedRow();
        //pegando o codigo da coluna da linha selecionada
        int codigoCliente = (int) tb_cliente.getValueAt(linha, 0);
        
        if(controllerCliente.excluirClienteController(codigoCliente)){
           JOptionPane.showMessageDialog(rootPane, "Cliente excluído com sucesso!", "ATENÇÃO!", JOptionPane.WARNING_MESSAGE);
            
           this.carregarCliente();
           this.habilitarDesabilitarCampo(false);
           this.limparCampos();
           
        }else{
            JOptionPane.showMessageDialog(rootPane, "Erro ao excluir Cliente!", "ERRO:", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btn_excluirActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        this.habilitarDesabilitarCampo(false);
        this.limparCampos();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    
    private void carregarCliente(){
        listaModelCliente = controllerCliente.getListaClienteController();
        //Usando o modelo padrão de tabela
        DefaultTableModel modelo = (DefaultTableModel)tb_cliente.getModel();
        //zerando linha 0 e setando os dados
        modelo.setNumRows(0);
        //inserir produtos na tabela
        int cont = listaModelCliente.size();
        //contador de tamanho da lista
        for (int i = 0; i < cont; i++) {
            //preenchendo col. e linha.
            modelo.addRow(new Object[]{
                listaModelCliente.get(i).getIdCliente(),
                listaModelCliente.get(i).getCliNome(),
                listaModelCliente.get(i).getCliCidade(),
                listaModelCliente.get(i).getCliTelFixo(),
            });
        }
    }
    
    /**
     * Limpar os campos do formulário
     */
    private void limparCampos(){
        txt_cliCod.setText("");
        txt_cliNome.setText("");
        txt_cliZona.setText("");
        txt_cliEndereco.setText("");
        txt_cliBairro.setText("");
        txt_cliCidade.setText("");
        //jCBox_cliEstados.setSelectedItem(modelCliente.getCliUf());
        jFT_cliCep.setText("");
        jFTF_cliTel_fixo.setText("");
        jFTF_cliTel_celular.setText("");
    }
    /**
     * Habilitando e Desabilitando campos depedendo da condição(true) ou (false)
     * @param condicao 
     */
    private void habilitarDesabilitarCampo(boolean condicao){
        //txt_cliCod.setEnabled(condicao);
        txt_cliNome.setEnabled(condicao);
        txt_cliZona.setEnabled(condicao);
        txt_cliEndereco.setEnabled(condicao);
        txt_cliBairro.setEnabled(condicao);
        txt_cliCidade.setEnabled(condicao);
        jCBox_cliEstados.setEnabled(condicao);
        jFT_cliCep.setEnabled(condicao);
        jFTF_cliTel_fixo.setEnabled(condicao);
        jFTF_cliTel_celular.setEnabled(condicao);
        btn_salva.setEnabled(condicao);
        //btn_altera.setEnabled(condicao);
        btn_cancelar.setEnabled(condicao);
        btn_excluir.setEnabled(condicao);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_altera;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_excluir;
    private javax.swing.JButton btn_novo;
    private javax.swing.JButton btn_salva;
    private javax.swing.JComboBox<String> jCBox_cliEstados;
    private javax.swing.JFormattedTextField jFTF_cliTel_celular;
    private javax.swing.JFormattedTextField jFTF_cliTel_fixo;
    private javax.swing.JFormattedTextField jFT_cliCep;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_cliente;
    private javax.swing.JTextField txt_cliBairro;
    private javax.swing.JTextField txt_cliCidade;
    private javax.swing.JTextField txt_cliCod;
    private javax.swing.JTextField txt_cliEndereco;
    private javax.swing.JTextField txt_cliNome;
    private javax.swing.JTextField txt_cliZona;
    // End of variables declaration//GEN-END:variables
}
